# Generated by Django 4.2.4 on 2023-08-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id_part', models.AutoField(primary_key=True, serialize=False)),
                ('name_part', models.CharField(max_length=250)),
                ('describe_part', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id_position', models.AutoField(primary_key=True, serialize=False)),
                ('name_position', models.CharField(max_length=250)),
                ('describe_position', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.TextField(null=True)),
                ('full_name', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=250)),
                ('wage', models.FloatField()),
                ('id_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.part')),
                ('id_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.position')),
            ],
        ),
        migrations.CreateModel(
            name='PartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.part')),
                ('id_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.position')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user')),
            ],
        ),
    ]
