# Generated by Django 4.2.4 on 2023-08-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='partdetail',
            old_name='id_part',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='partdetail',
            old_name='id_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_part',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_position',
            new_name='position',
        ),
    ]
