# Generated by Django 4.2.4 on 2023-08-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_rename_id_user_account_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='usernamee',
        ),
    ]
