# Generated by Django 4.2.4 on 2023-08-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_rename_username_account_usernamee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='usernamee',
            new_name='username',
        ),
    ]
