# Generated by Django 4.2.4 on 2023-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0004_rename_usernamee_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(default='x', max_length=250),
            preserve_default=False,
        ),
    ]
