# Generated by Django 4.2.4 on 2023-10-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0005_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
