# Generated by Django 4.2.4 on 2023-10-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='key',
            field=models.TextField(default=1984),
            preserve_default=False,
        ),
    ]
