# Generated by Django 4.2.4 on 2023-08-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_service', '0002_rename_user_post_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userr',
            new_name='user',
        ),
    ]
