# Generated by Django 4.2.4 on 2023-09-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_service', '0003_rename_userr_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_post',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='type_post',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
