# Generated by Django 4.2.4 on 2023-08-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id_setting', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('overtime', models.FloatField()),
                ('holiday', models.FloatField()),
                ('day_off', models.FloatField()),
            ],
        ),
    ]
