# Generated by Django 4.2.4 on 2023-10-03 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0004_rename_usernamee_account_username'),
        ('post_service', '0004_post_header_post_post_type_post'),
        ('comment_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post_service.post'),
        ),
        migrations.CreateModel(
            name='UserRead',
            fields=[
                ('id_read', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_service.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user')),
            ],
        ),
    ]
