# Generated by Django 4.2.4 on 2023-08-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_service', '0002_rename_id_user_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_post',
            new_name='post',
        ),
    ]
