# Generated by Django 4.2.4 on 2023-09-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_service', '0004_rename_usernamee_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id_calendar', models.AutoField(primary_key=True, serialize=False)),
                ('header_calendar', models.CharField(max_length=250)),
                ('body_calendar', models.TextField()),
                ('type_calendar', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('day_calendar', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.part')),
            ],
        ),
    ]
