# Generated by Django 4.2.4 on 2023-10-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_service', '0007_account_key'),
        ('post_service', '0004_post_header_post_post_type_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('title_notification', models.CharField(max_length=250)),
                ('body_notification', models.CharField(max_length=250)),
                ('time_notification', models.DateTimeField()),
                ('type_notification', models.IntegerField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_service.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user')),
            ],
        ),
    ]
