# Generated by Django 4.2.4 on 2023-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0002_notificationpost_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpost',
            name='post',
        ),
        migrations.AddField(
            model_name='notificationpost',
            name='id_data',
            field=models.IntegerField(default=1988),
            preserve_default=False,
        ),
    ]
