# Generated by Django 4.2.4 on 2023-10-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_service', '0007_account_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOut',
            fields=[
                ('id_time_out', models.AutoField(primary_key=True, serialize=False)),
                ('day_out', models.DateField()),
                ('time_out', models.TimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user')),
            ],
        ),
        migrations.CreateModel(
            name='TimeIn',
            fields=[
                ('id_time_in', models.AutoField(primary_key=True, serialize=False)),
                ('day_in', models.DateField()),
                ('time_in', models.TimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user')),
            ],
        ),
    ]
