# Generated by Django 4.2.4 on 2023-08-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timein',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='timeout',
            old_name='id_user',
            new_name='user',
        ),
    ]
